server:
  port: 7100

eureka:
  client:
    healthcheck:
        enabled: true

    service-url:
#      defaultZone: http://localhost:8761/eureka
       defaultZone: http://qinqiuqiu:123@localhost:8761/eureka #enreka server 后台支持口令认证
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

logging:
  level:
    root: INFO
    org.troy: DEBUG

spring:
  application:
    name: consumer-movie-service

#配置文件中访问微服务provider-user-service; 使用随机负载均衡算法
provider-user-service:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
      listOfServers: localhost:7001,localhost:7000 #设置ribbon访问的微服务地址

#ribbon 禁止使用eureka(获取eureka拉取服务列表)
ribbon:
  eureka:
    enabled: false